import {createSlice, PayloadAction} from "@reduxjs/toolkit";


interface NumberState {
    number: number;
    computers: string[]; // Example type for `computers`
}

const initialState: NumberState = {
    number: 0,
    computers: []
}
const numberSlice = createSlice({
    name: "number",
    initialState,
    reducers: {
        increment: (state, action: PayloadAction<number>) => ({
            ...state,
            number: state.number + action.payload
        }),
        decrement: (state, action : any)=>({
            ...state,
            number: state.number - action.payload
        })
    }
})

//destructure actions from the above slice
export const {increment, decrement} = numberSlice.actions

//export default the main reducer, this will be parse to the store, this contain all the reducers above (this will generated by the redux toolkit)
export default numberSlice.reducer;